name: simple workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  jobId1:
    name: simple print
    runs-on: ubuntu-latest
    steps:
      - name: simple echo print
        id: echoPrint
        run: echo "Echo Print complete"

      - name: simple python print
        id: pyPrint
        shell: python #can be cmd prompt or anyother shell commands
        run: print("print in python print statement sum of 12 n 11 =",12+11)

      - name: multi line echo 
        id: multiLineEcho
        shell: cmd
        run: |
          echo line 1 echo
          echo line 2 echo
        
        
